name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read    # za checkout koda
  pages: write      # za konfigurisanje i deploy na Pages
  id-token: write   # za deploy_pages akciju

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18.x'    # koristimo Node 18 (može i druga verzija)
          # cache: 'npm'         # <- Ne uključujemo keš da izbegnemo grešku sa lock fajlom

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # (u novijim verzijama automatski koristi GITHUB_TOKEN iz permissions)
